# Generated by Django 4.2.27 on 2025-12-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão devolução'),
        ),
    ]
