# Generated by Django 4.2.27 on 2025-12-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_numero_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_livros/'),
        ),
    ]
