# Generated by Django 4.2.27 on 2026-01-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editoras', '0001_initial'),
        ('livros', '0003_livro_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.AddField(
            model_name='livro',
            name='editora_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editoras.editora', verbose_name='Editora'),
        ),
    ]
