# Generated by Django 4.2.27 on 2026-01-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_livro_editora_livro_editora_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='editora_id',
            new_name='editora',
        ),
    ]
